[package]
name = 'calculator_l05'
version = '1.0.0'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }

[addresses]
metaschool = "0x8292debbee060acaeb64b2fcd5662db8bc6be3be0d33f735b2f66144bd46d89a"
std = "0x1"